default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ --verbose, --strict, feat, fix, chore, style, test, build, ci, docs, wip ]
        fail_fast: true
  - repo: local
    hooks:
      - id: run_tests
        name: run_tests
        files: \.py$
        language: script
        entry: ./run_tests.sh
        stages: [ pre-commit ]
        fail_fast: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    # Pyright version.
    rev: v1.1.398
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.10
    hooks:
      - id: uv-lock
