"""Define initial tables

Revision ID: 57caef39c258
Revises: 
Create Date: 2025-04-01 21:46:37.543911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57caef39c258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('gain', 'offset', 'pressure', 'temp', name='calibrationtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('calibration_tag_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calibration_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_tag_associations_archived_at'), 'calibration_tag_associations', ['archived_at'], unique=False)
    op.create_index(op.f('ix_calibration_tag_associations_calibration_id'), 'calibration_tag_associations', ['calibration_id'], unique=False)
    op.create_index(op.f('ix_calibration_tag_associations_created_at'), 'calibration_tag_associations', ['created_at'], unique=False)
    op.create_index(op.f('ix_calibration_tag_associations_tag_id'), 'calibration_tag_associations', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibration_tag_associations_tag_id'), table_name='calibration_tag_associations')
    op.drop_index(op.f('ix_calibration_tag_associations_created_at'), table_name='calibration_tag_associations')
    op.drop_index(op.f('ix_calibration_tag_associations_calibration_id'), table_name='calibration_tag_associations')
    op.drop_index(op.f('ix_calibration_tag_associations_archived_at'), table_name='calibration_tag_associations')
    op.drop_table('calibration_tag_associations')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('calibrations')
    # ### end Alembic commands ###
