name: Pyright

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/pyright.yaml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/pyright.yaml"
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv (and Python)
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          pyproject-file: "pyproject.toml"

      # Create venv and install deps via uv
      - name: Set up virtualenv and install deps
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv sync --frozen

      # Run pyright
      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          python-platform: "Linux"
          python-version: "3.12"
