name: Ruff
on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/ruff.yaml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/ruff.yaml"
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check --extend-exclude alembic/**/* tests/**/* --config pyproject.toml src
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --config pyproject.toml src
